=== LumineInteyvat/ISR-hw3-fanfraction-skill/.skills/story-info-collector/schemas/extracted_document.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": ["document_id", "source_type", "source_name", "source_url", "language", "character", "work", "category", "title", "text", "metadata", "collected_at"],
  "properties": {
    "document_id": {"type": "string"},
    "source_type": {"type": "string"},
    "source_name": {"type": "string"},
    "source_url": {"type": "string"},
    "language": {"type": "string"},
    "character": {"type": "string"},
    "work": {"type": "string"},
    "category": {"type": "string"},
    "title": {"type": "string"},
    "text": {"type": "string"},
    "metadata": {"type": "object"},
    "collected_at": {"type": "string"}
  }
}

=== LumineInteyvat/ISR-hw3-fanfraction-skill/docs/character-information/yuan-shen__fu-zhu-na__character-information__fandom__7242c3a68999.json
{
  "document_id": "doc_8cc670354934ba18",
  "source_type": "official_reference",
  "source_name": "Crawlbase Fandom",
  "source_url": "https://genshin-impact.fandom.com/wiki/Furina",
  "language": "zh",
  "character": "芙宁娜",
  "work": "原神",
  "category": "character-information",
  "title": "Furina | Genshin Impact Wiki | Fandom",
  "text": "Furina ‍ English Introduced as the flamboyant and overconfident Hydro Archon , Furina's theatrics are eventually revealed to be a public persona, which she later discards in favor of living a relatively humbler life as an actress and artistic consultant. Contents Ascension Phase Level Base HP ‍Base ATK ‍ ‍ Charged Attack Consumes a certain amount of Stamina to unleash a solo dance, dealing Physical DMG to nearby opponents and changing her Arkhe alignment. If Salon Members or Singer of Many Waters summoned by her Elemental Skill \" Salon Solitaire \" are present, their lineup will switch in response. Arkhe: Seats Sacred and Secular At intervals, when Furina's Normal Attacks hit, a Spiritbreath Thorn or a Surging Blade will descend based on her current alignment, dealing Hydro DMG based on her current alignment. When Furina takes the field, her starting Arkhe will be Ousia . Plunging Attack Plunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact. Unlike all other Sword users, Furina's Charged Attack is not preceded by a Normal Attack. The cooldowns for Spiritbreath Thorn and Surging Blade are separate. Furina has special visual and audio effects when performing a Plunging Attack into or onto water without transitioning into swimming , such as when her Elemental Skill is active or when plunging into shallow water. The visual effect appears even if her Elemental Skill is not active. The audio effect only plays when performing a High Plunge. Constellation Effects Constellation Level 6, \"Hear Me — Let Us Raise the Chalice of Love!\" : \"When using Salon Solitaire , Furina gains 'Center of Attention' for 10s. Throughout the duration, Furina's Normal Attacks, Charged Attacks, and Plunging Attacks are converted into Hydro DMG which cannot be overridden by any other elemental infusion. DMG is also increased by an amount equivalent to 18% of Furina's max HP . Throughout the duration, Furina's Normal Attacks (not including Arkhe: Seats Sacred and Secular Attacks), Charged Attacks, and the impact of Plunging Attacks will cause different effects up to every 0.1s after hitting opponents depending on her current Arkhe alignment: Arkhe: Ousia Every 1s, all nearby characters in the party will be healed by 4% of Furina's max HP, for a duration of 2.9s. Triggering this effect again will extend its duration. Arkhe: Pneuma This Normal Attack (not including Arkhe: Seats Sacred and Secular Attacks), Charged Attack, or Plunging Attack ground impact DMG will be further increased by an amount equivalent to 25% of Furina's max HP. When any of the attacks mentioned previously hit an opponent, all nearby characters in the party will consume 1% of their current HP. During the duration of each instance of 'Center of Attention,' the above effects can be triggered up to 6 times. 'Center of Attention' will end when its effects have triggered 6 times or when the duration expires.\" ‍ ‍Type ‍ 6s/6s Plunging Attack (Ousia) Preview Invites the guests of the Salon Solitaire to come forth and aid in Furina's performance. Will summon either the Salon Members or the Singer of Many Waters based on Furina's current Arkhe alignment. Ousia Foaming bubbles like celebrants shall dance, dealing AoE Hydro DMG based on Furina's Max HP and summoning 3 Salon Members: the Ball Octopus-shaped Gentilhomme Usher, the Bubbly Seahorse-shaped Surintendante Chevalmarin, and the Armored Crab-shaped Mademoiselle Crabaletta. They will attack nearby opponents at intervals, prioritizing the target of the active character, dealing Hydro DMG based on Max HP. When they attack, if character(s) with more than 50% HP are nearby, the Members will increase their current attack's power based on the number of such characters, and consume said characters' HP. If the characters who meet these requirements are 1/2/3/4 (or more), the Members' attacks will deal 110%/120%/130%/140% of their original DMG. Pneuma Summons the Singer of Many Waters, who will heal nearby active character(s) based on Max HP at intervals. The Salon Members and Singer of Many Waters share a duration, and when Furina uses her Charged Attack to change the guest type, the new guests will inherit the initial duration. While the Salon Members and the Singer of Many Waters are on the field, Furina can move on the water 's surface. When a Salon Member's attack hits at least one enemy , it generates 1 Elemental Particle . This particle generation has a cooldown of 2.5 seconds. In Co-Op Mode , only one instance of Furina's Elemental Skill can exist at a time. The last player to use this skill will replace the already existing instance. Overriding another player's Elemental Skill will also remove their ability to walk on water. Only the last player to use this skill can change which version of the skill is active via Furina's Arkhe alignment. The Singer of Many Waters will heal nearby active characters every 2s. Salon Members drain HP when they attack, not when they hit a target. The HP drain will still occur even if the attack misses. Salon Members will attack non-enemy targetable objects like campfires and Pneumousia Relays . Salon Members have the same AI mechanics as enemies. See Cooldown#Enemy Cooldowns for more information on how their cooldowns function. Salon Member AI Logic Gentilhomme Usher Will attack if target is within 6m, with 2.9s CD. Will teleport near target if out of range, with 1.5s CD. Surintendante Chevalmarin Will attack if target is within 9.5m, with 1.19s CD. Will teleport near target if out of range, with 1.5s CD. Has 0.5s global CD for both teleporting and attacking. Mademoiselle Crabaletta Will attack if target is within 20m, with 4.8s CD. Will teleport near target if out of range, with 1.5s CD. Pneuma Icon Passive Effects Passive Talent 2, Unheard Confession : \"Every 1,000 points of Furina's Max HP can buff the different Arkhe-aligned Salon Solitaire in the following ways: Will increase Salon Member DMG dealt by 0.7%, up to a maximum of 28%. Will decrease active character healing interval of the Singer of Many Waters by 0.4%, up to a maximum of 16%.\" Constellation Effects Constellation Level 4, \"They Know Not Life, Who Dwelt in the Netherworld Not!\" : \"When the Salon Members from Salon Solitaire hit an opponent, or the Singer of Many Waters restores HP to nearby active characters, Furina will restore 4 Energy . This effect can be triggered once every 5s.\" Constellation Level 5, Constellation Level 6, \"Hear Me — Let Us Raise the Chalice of Love!\" : During the first 10 seconds after using Salon Solitaire, Furina's first six Normal, Charged, or Plunging Attacks are converted into Hydro DMG, have their damage increased based on Furina's Max HP, and grant different effects based on Furina's Arkhe alignment when each attack is started. If Furina is aligned with Ousia, all nearby characters are briefly healed over time. If Furina is aligned with Pneuma, all nearby characters lose 1% of their current HP and the attack's damage receives another increase based on Furina's Max HP. ‍ ‍Type ‍ 7.86 8.45 9.04 9.83 10.42 11.01 11.8 12.58 13.37 14.16 14.94 15.73 16.71 17.7 Duration 30s 5.96 6.41 6.85 7.45 7.9 8.34 8.94 9.54 10.13 10.73 11.32 11.92 12.67 13.41 3.23 3.47 3.72 4.04 4.28 4.52 4.85 5.17 5.49 5.82 6.14 6.46 6.87 7.27 8.29 8.91 9.53 10.36 10.98 11.6 12.43 13.26 14.09 14.92 15.75 16.58 17.61 18.65 2.4 1.6 3.6 4.8% Max HP Preview Rouses the impulse to revel, creating a stage of foam that will deal AoE Hydro DMG based on Furina's Max HP and cause nearby party members to enter the Universal Revelry state: During this time, when nearby party members' HP increases or decreases, 1 Fanfare point will be granted to Furina for each percentage point of their Max HP by which their HP changes. At the same time, Furina will increase the DMG dealt by and Incoming Healing Bonus of all nearby party members based on the amount of Fanfare she has. When the duration ends, Furina's Fanfare points will be cleared. An indicator will appear on screen upon reaching 25%, 50%, 75%, and 100% of the maximum Fanfare points. At 25%, 50%, and 75%, the indicator is a crowd that pops up from the bottom of the screen. At 100%, the indicator is a screen flash. If an HP drain effect is negated by Invincibility Frames during Elemental Bursts or Mirror Reflection of Doom 's hold mode, Fanfare Stacks will not increase due to said effect. When recasting while Universal Revelry is still in effect, the Fanfare stacks will reset before the Skill DMG hits. [8] Reviving a fallen party member will count as HP change and grant Fanfare stacks. [8] Constellation Effects Constellation Level 1, Constellation Level 2, \"A Woman Adapts Like Duckweed in Water\" : \"While Let the People Rejoice lasts, Furina's Fanfare gain from increases or decreases in nearby characters' HP is increased by 250%. Each point of Fanfare above the limit will increase Furina's Max HP by 0.35%. Her maximum Max HP increase is 140%.\" Constellation Level 3, ‍ ‍Type ‍ 0.07 0.09 0.11 0.13 0.15 0.17 0.19 0.21 0.23 0.25 0.27 0.29 0.31 0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 0.11 0.12 0.13 CD 15s Gameplay Notes When the active character in your party receives healing , if the source of the healing is not Furina herself and the healing overflows, then Furina will heal nearby party members for 2% of their Max HP once every 2s within the next 4s. Healing from another player's Furina in Co-Op Mode counts as a source that is \"not Furina herself.\" This applies for the healing from both her Elemental Skill and this Ascension Passive. Gameplay Notes Every 1,000 points of Furina's
